// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package image_classify

type NewProject struct {
	Name   string `json:"name"`
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
